-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     name VARCHAR(20) NOT NULL,
                                     CONSTRAINT roles_name_key UNIQUE (name)
);

-- Create users table
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     username VARCHAR(20) NOT NULL UNIQUE,
                                     email VARCHAR(50) NOT NULL UNIQUE,
                                     password VARCHAR(120) NOT NULL
);

-- Create user_roles table for many-to-many relationship
CREATE TABLE IF NOT EXISTS user_roles (
                                          user_id BIGINT NOT NULL,
                                          role_id BIGINT NOT NULL,
                                          PRIMARY KEY (user_id, role_id),
                                          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                          FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);
